### PR TITLE
Missing node-labels

### PR DESCRIPTION
**Pull request by akaija**
Log-file names now include node.

### CODE REVIEW

**Comment by akaija** [comment]
Should I have some sort of label to distinguish between queues and clusters? Are there nodes with the same name on different queues/clusters?

**Comment by paulboone** [comment]
I don't think there are nodes with the same name on different clusters. Maybe you have two nodes named n3, for example, but uname -n  will return something like n3.mpi.sam.pitt.edu so will include the cluster. But... you should try to double-check this, because your instinct is totally correct.

**Comment by akaija** [comment]
Ok, I need to revise this... right now I only get "n3"

**Comment by akaija** [comment]
I'm having trouble getting the hostname from which the job was started... on the login node $HOSTNAME/uname -n shows login0b.frank.sam.pitt.edu but on an interactive node I only get something like n6.

**Comment by paulboone** [comment]
Well n6 is basically ok… as long as it is different from n6 on frank. Or
you would have to only use one cluster at a time.

On November 16, 2016 at 6:28:27 PM, A Reino Kaija (notifications@github.com)
wrote:

I'm having trouble getting the hostname from which the job was started...
on the login node $HOSTNAME/uname -n shows login0b.frank.sam.pitt.edu but
on an interactive node I only get something like n6.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/WilmerLab/HTSOHM-dev/pull/21#issuecomment-261106421,
or mute the thread

**Pull request closed without merging**
